-- Migration: Add 15 more venue records for Delhi, Mumbai, and Bengaluru
-- Date: 2024-01-04

-- Insert 15 additional venue records with realistic Indian venue data
INSERT INTO venues (
  name, 
  city, 
  capacity, 
  price_per_person, 
  venue_type, 
  amenities, 
  rating, 
  description,
  contact_phone,
  contact_email,
  address,
  parking_capacity,
  catering_available,
  wifi_available,
  ac_available,
  availability_status,
  amenities_json
) VALUES

-- DELHI VENUES (5)
(
  'The Imperial New Delhi',
  'Delhi',
  180,
  5800.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'valet_service', 'spa_access'],
  4.8,
  'Historic luxury hotel with colonial architecture and world-class service',
  '+91-11-2334-1234',
  'events@theimperialnewdelhi.com',
  'Janpath, Connaught Place, New Delhi, Delhi 110001',
  120,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "valet_service", "spa_access", "heritage_ambiance", "garden_access", "business_center"]'
),

(
  'India Habitat Centre',
  'Delhi',
  350,
  3200.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'exhibition_space', 'meeting_rooms'],
  4.5,
  'Modern convention center with state-of-the-art facilities and flexible spaces',
  '+91-11-2468-1234',
  'events@indiahabitat.org',
  'Lodhi Road, Near Jor Bagh Metro, New Delhi, Delhi 110003',
  200,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "exhibition_space", "meeting_rooms", "tech_support", "green_rooms"]'
),

(
  'The Leela Palace New Delhi',
  'Delhi',
  220,
  6200.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access', 'pool_access'],
  4.9,
  'Palatial luxury hotel with royal treatment and exceptional dining',
  '+91-11-3933-1234',
  'events@theleela.com',
  'Diplomatic Enclave, Chanakyapuri, New Delhi, Delhi 110023',
  150,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "pool_access", "royal_ambiance", "concierge"]'
),

(
  'Pragati Maidan Convention Centre',
  'Delhi',
  500,
  2800.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'exhibition_space', 'loading_dock'],
  4.4,
  'Large-scale convention center perfect for major exhibitions and events',
  '+91-11-2337-1234',
  'events@pragatimaidan.com',
  'Pragati Maidan, Mathura Road, New Delhi, Delhi 110002',
  400,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "exhibition_space", "loading_dock", "meeting_rooms", "tech_support"]'
),

(
  'The Taj Palace Hotel',
  'Delhi',
  280,
  5500.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access', 'garden_access'],
  4.7,
  'Elegant palace hotel with stunning gardens and luxury amenities',
  '+91-11-2611-1234',
  'events@tajpalace.com',
  'Sardar Patel Marg, Diplomatic Enclave, New Delhi, Delhi 110021',
  180,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "garden_access", "heritage_tour", "cultural_show"]'
),

-- MUMBAI VENUES (5)
(
  'The Taj Mahal Palace Mumbai',
  'Mumbai',
  250,
  6800.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access', 'sea_view'],
  4.9,
  'Iconic luxury hotel with breathtaking Arabian Sea views and heritage charm',
  '+91-22-6665-1234',
  'events@tajhotels.com',
  'Apollo Bunder, Colaba, Mumbai, Maharashtra 400001',
  160,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "sea_view", "heritage_ambiance", "concierge"]'
),

(
  'Bombay Exhibition Centre',
  'Mumbai',
  450,
  3000.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'exhibition_space', 'tech_support'],
  4.3,
  'Modern exhibition center with flexible spaces for large-scale events',
  '+91-22-2493-1234',
  'events@bombayexhibition.com',
  'Goregaon East, Mumbai, Maharashtra 400063',
  300,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "exhibition_space", "tech_support", "meeting_rooms", "loading_dock"]'
),

(
  'ITC Grand Central',
  'Mumbai',
  200,
  4800.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access', 'business_center'],
  4.6,
  'Premium business hotel with excellent connectivity and modern amenities',
  '+91-22-2410-1234',
  'events@itchotels.com',
  'Dr. Babasaheb Ambedkar Road, Parel, Mumbai, Maharashtra 400012',
  120,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "business_center", "fitness_center", "concierge"]'
),

(
  'Sahara Star Hotel',
  'Mumbai',
  180,
  4200.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'pool_access', 'garden_access'],
  4.4,
  'Contemporary hotel with unique dome architecture and lush gardens',
  '+91-22-3980-1234',
  'events@saharastar.com',
  'Domestic Airport, Vile Parle East, Mumbai, Maharashtra 400099',
  100,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "pool_access", "garden_access", "airport_proximity", "spa_access"]'
),

(
  'World Trade Centre Mumbai',
  'Mumbai',
  320,
  3500.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'exhibition_space', 'meeting_rooms'],
  4.5,
  'Premier business center with world-class conference facilities',
  '+91-22-6652-1234',
  'events@wtcmumbai.com',
  'Cuffe Parade, Colaba, Mumbai, Maharashtra 400005',
  200,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "exhibition_space", "meeting_rooms", "business_center", "tech_support"]'
),

-- BENGALURU VENUES (5)
(
  'The Leela Palace Bengaluru',
  'Bengaluru',
  240,
  5900.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access', 'pool_access'],
  4.8,
  'Luxury palace hotel with royal treatment and exceptional service',
  '+91-80-2521-1234',
  'events@theleela.com',
  '23, Airport Road, Bangalore, Karnataka 560008',
  160,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "pool_access", "royal_ambiance", "garden_access"]'
),

(
  'UB City Mall Convention Centre',
  'Bengaluru',
  280,
  3800.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'shopping_access', 'meeting_rooms'],
  4.4,
  'Premium convention center within luxury shopping complex',
  '+91-80-4177-1234',
  'events@ubcity.com',
  'UB City, Vittal Mallya Road, Bangalore, Karnataka 560001',
  180,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "shopping_access", "meeting_rooms", "luxury_ambiance", "concierge"]'
),

(
  'ITC Gardenia',
  'Bengaluru',
  200,
  5200.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access', 'garden_access'],
  4.7,
  'Eco-friendly luxury hotel with beautiful gardens and sustainable practices',
  '+91-80-2211-1234',
  'events@itchotels.com',
  'Residency Road, Bangalore, Karnataka 560025',
  130,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "garden_access", "eco_friendly", "fitness_center"]'
),

(
  'Bangalore International Exhibition Centre',
  'Bengaluru',
  400,
  3200.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'exhibition_space', 'tech_support'],
  4.3,
  'Large-scale exhibition center with modern technology and flexible spaces',
  '+91-80-4111-1234',
  'events@biec.com',
  'Tumkur Road, Bangalore, Karnataka 560073',
  250,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "exhibition_space", "tech_support", "meeting_rooms", "loading_dock"]'
),

(
  'The Ritz-Carlton Bangalore',
  'Bengaluru',
  160,
  6500.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access', 'pool_access'],
  4.9,
  'Ultra-luxury hotel with impeccable service and world-class amenities',
  '+91-80-4914-1234',
  'events@ritzcarlton.com',
  '99, Residency Road, Bangalore, Karnataka 560025',
  100,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "pool_access", "luxury_service", "concierge"]'
);

-- Create additional indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_venues_city_capacity ON venues(city, capacity);
CREATE INDEX IF NOT EXISTS idx_venues_price_rating ON venues(price_per_person, rating);

-- Add comments for the new venues
COMMENT ON TABLE venues IS 'Updated venues table with 27 total venues across major Indian cities';
