-- Migration: Add 15 new venue records with realistic Indian venue data
-- Date: 2024-01-03

-- Insert 15 new venue records with realistic Indian venue data
INSERT INTO venues (
  name, 
  city, 
  capacity, 
  price_per_person, 
  venue_type, 
  amenities, 
  rating, 
  description,
  contact_phone,
  contact_email,
  address,
  parking_capacity,
  catering_available,
  wifi_available,
  ac_available,
  availability_status,
  amenities_json
) VALUES

-- DELHI VENUES
(
  'The Imperial Ballroom',
  'Delhi',
  120,
  4500.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'valet_service'],
  4.7,
  'Elegant colonial-era ballroom in the heart of Delhi with heritage charm',
  '+91-11-2334-1234',
  'events@theimperialnewdelhi.com',
  'Janpath, Connaught Place, New Delhi, Delhi 110001',
  80,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "valet_service", "heritage_ambiance", "garden_access"]'
),

(
  'Pragati Maidan Convention Center',
  'Delhi',
  400,
  2800.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'exhibition_space'],
  4.5,
  'Large-scale convention center perfect for corporate events and exhibitions',
  '+91-11-2337-1234',
  'events@pragatimaidan.com',
  'Pragati Maidan, Mathura Road, New Delhi, Delhi 110002',
  300,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "exhibition_space", "meeting_rooms", "tech_support"]'
),

(
  'Lodhi Garden Banquet Hall',
  'Delhi',
  80,
  3500.00,
  'banquet_hall',
  ARRAY['parking', 'catering', 'audiovisual', 'garden_access'],
  4.6,
  'Intimate banquet hall with beautiful garden views and outdoor seating',
  '+91-11-2461-1234',
  'events@lodhigarden.com',
  'Lodhi Road, Near India Habitat Centre, New Delhi, Delhi 110003',
  60,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "garden_access", "outdoor_seating", "natural_lighting"]'
),

-- MUMBAI VENUES
(
  'Trident BKC Grand Ballroom',
  'Mumbai',
  200,
  5200.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'spa_access'],
  4.8,
  'Luxury ballroom in Bandra Kurla Complex with modern amenities and city views',
  '+91-22-6778-1234',
  'events@tridenthotels.com',
  'Bandra Kurla Complex, Bandra East, Mumbai, Maharashtra 400051',
  150,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "spa_access", "city_views", "business_center"]'
),

(
  'NCPA Tata Theatre',
  'Mumbai',
  150,
  3800.00,
  'auditorium',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'professional_stage'],
  4.7,
  'Professional theatre venue with excellent acoustics and stage facilities',
  '+91-22-2282-1234',
  'events@ncpa-mumbai.com',
  'Nariman Point, Marine Drive, Mumbai, Maharashtra 400021',
  100,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "professional_stage", "acoustics", "green_rooms"]'
),

(
  'Worli Sea Face Banquet',
  'Mumbai',
  100,
  4200.00,
  'banquet_hall',
  ARRAY['parking', 'catering', 'audiovisual', 'sea_view'],
  4.4,
  'Elegant banquet hall with stunning Arabian Sea views and outdoor terrace',
  '+91-22-2492-1234',
  'events@worliseaface.com',
  'Worli Sea Face, Worli, Mumbai, Maharashtra 400018',
  70,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "sea_view", "outdoor_terrace", "valet_service"]'
),

-- BENGALURU VENUES
(
  'UB City Crystal Ballroom',
  'Bengaluru',
  180,
  4800.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'shopping_access'],
  4.6,
  'Sophisticated ballroom in UB City with luxury shopping and dining options',
  '+91-80-4177-1234',
  'events@ubcity.com',
  'UB City, Vittal Mallya Road, Bengaluru, Karnataka 560001',
  120,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "shopping_access", "luxury_ambiance", "concierge"]'
),

(
  'Bangalore International Centre',
  'Bengaluru',
  250,
  3200.00,
  'conference_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'tech_support'],
  4.5,
  'Modern conference center with state-of-the-art technology and flexible spaces',
  '+91-80-4111-1234',
  'events@bangaloreinternational.com',
  'Domlur, Bengaluru, Karnataka 560071',
  200,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "tech_support", "meeting_rooms", "presentation_equipment"]'
),

(
  'Cubbon Park Garden Venue',
  'Bengaluru',
  60,
  2800.00,
  'outdoor',
  ARRAY['parking', 'catering', 'natural_setting'],
  4.3,
  'Charming outdoor venue in the heart of Cubbon Park with natural beauty',
  '+91-80-2286-1234',
  'events@cubbonpark.com',
  'Cubbon Park, MG Road, Bengaluru, Karnataka 560001',
  40,
  true,
  false,
  false,
  'available',
  '["parking", "catering", "natural_setting", "garden_access", "outdoor_seating", "landscaping"]'
),

-- CHENNAI VENUES
(
  'Park Hyatt Grand Ballroom',
  'Chennai',
  160,
  4600.00,
  'hotel',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'pool_access'],
  4.7,
  'Luxury hotel ballroom with contemporary design and excellent service',
  '+91-44-7177-1234',
  'events@parkhyattchennai.com',
  '39, Velachery Road, Guindy, Chennai, Tamil Nadu 600032',
  100,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "pool_access", "spa_access", "business_center"]'
),

(
  'Chennai Trade Centre',
  'Chennai',
  350,
  2400.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'exhibition_space'],
  4.4,
  'Large convention center with multiple halls and exhibition facilities',
  '+91-44-2250-1234',
  'events@chennaitradecentre.com',
  'Nandambakkam, Chennai, Tamil Nadu 600089',
  250,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "exhibition_space", "meeting_rooms", "loading_dock"]'
),

(
  'Adyar Bridge Club',
  'Chennai',
  90,
  3100.00,
  'banquet_hall',
  ARRAY['parking', 'catering', 'audiovisual', 'river_view'],
  4.2,
  'Intimate banquet hall with Adyar River views and elegant interiors',
  '+91-44-2441-1234',
  'events@adyarbridgeclub.com',
  'Adyar Bridge, Adyar, Chennai, Tamil Nadu 600020',
  60,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "river_view", "elegant_interiors", "intimate_setting"]'
),

-- HYDERABAD VENUES
(
  'Taj Falaknuma Palace',
  'Hyderabad',
  120,
  6500.00,
  'heritage',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'heritage_tour'],
  4.9,
  'Historic palace venue with royal ambiance and breathtaking city views',
  '+91-40-6669-1234',
  'events@tajfalaknuma.com',
  'Engine Bowli, Falaknuma, Hyderabad, Telangana 500053',
  80,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "heritage_tour", "royal_ambiance", "city_views"]'
),

(
  'HICC Novotel',
  'Hyderabad',
  280,
  3400.00,
  'convention_center',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'tech_support'],
  4.6,
  'Modern convention center with cutting-edge technology and flexible spaces',
  '+91-40-6682-1234',
  'events@hiccnovotel.com',
  'HITEC City, Madhapur, Hyderabad, Telangana 500081',
  200,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "tech_support", "meeting_rooms", "presentation_equipment"]'
),

(
  'Golkonda Resort Banquet',
  'Hyderabad',
  140,
  3800.00,
  'resort',
  ARRAY['parking', 'catering', 'audiovisual', 'wifi', 'pool_access'],
  4.4,
  'Resort-style banquet hall with outdoor spaces and recreational facilities',
  '+91-40-2355-1234',
  'events@golkondaresort.com',
  'Golkonda Fort Road, Hyderabad, Telangana 500008',
  100,
  true,
  true,
  true,
  'available',
  '["parking", "catering", "audiovisual", "wifi", "pool_access", "outdoor_spaces", "recreational_facilities"]'
);

-- Create additional indexes for better query performance on new data
CREATE INDEX IF NOT EXISTS idx_venues_capacity_range ON venues(capacity) WHERE capacity BETWEEN 50 AND 500;
CREATE INDEX IF NOT EXISTS idx_venues_price_range ON venues(price_per_person) WHERE price_per_person BETWEEN 2000 AND 8000;

-- Add comments for the new venues
COMMENT ON TABLE venues IS 'Updated venues table with 25 total venues across major Indian cities';
